In [1]:
import numpy as np    #ZADANIE1
A=np.array([[1,0,1,2],[0,1,-2,0]])
A

array([[ 1,  0,  1,  2],
       [ 0,  1, -2,  0]])

In [2]:
B=np.array([[1,2,1,0],[1,0,-1,1],[2,1,0,0]])
B

array([[ 1,  2,  1,  0],
       [ 1,  0, -1,  1],
       [ 2,  1,  0,  0]])

In [3]:
C=np.array([[1,2,1,0],[1,0,-1,1],[2,1,0,0],[2,2,0,1]])
C

array([[ 1,  2,  1,  0],
       [ 1,  0, -1,  1],
       [ 2,  1,  0,  0],
       [ 2,  2,  0,  1]])

In [4]:
D=np.array([[1,0,2],[0,2,1]])
D

array([[1, 0, 2],
       [0, 2, 1]])

In [5]:
E=np.array([[1,0,-1],[-1,2,2]])
E

array([[ 1,  0, -1],
       [-1,  2,  2]])

In [6]:
F=np.array([[0,3],[2,1]])
F

array([[0, 3],
       [2, 1]])

In [7]:
G=np.array([[2,0,3],[-1,1,2],[0,1,-1]])
G

array([[ 2,  0,  3],
       [-1,  1,  2],
       [ 0,  1, -1]])

In [8]:
H=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
H

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
I=np.array([[1,0],[0,1]])
I

array([[1, 0],
       [0, 1]])

In [10]:
w=np.array([[1,2,1,0]])
w

array([[1, 2, 1, 0]])

In [11]:
u=np.array([[1,0,-1,1]])
u

array([[ 1,  0, -1,  1]])

In [12]:
v=np.array([[2,1,0,0]])
v

array([[2, 1, 0, 0]])

In [13]:
x=np.array([[4,4,4]])
x

array([[4, 4, 4]])

In [14]:
z=np.array([[1,2,1,2]])
z

array([[1, 2, 1, 2]])

In [15]:
D+E     #ZADANIE2

array([[ 2,  0,  1],
       [-1,  4,  3]])

In [16]:
D@E.T

array([[-1,  3],
       [-1,  6]])

In [17]:
D.T@E

array([[ 1,  0, -1],
       [-2,  4,  4],
       [ 1,  2,  0]])

In [18]:
F@F

array([[6, 3],
       [2, 7]])

In [19]:
G@G@G@G

array([[  4,  21,  12],
       [-18,   0, -27],
       [ -7,  -3,   6]])

In [20]:
(D@E.T)+F

array([[-1,  6],
       [ 1,  7]])

In [21]:
-G

array([[-2,  0, -3],
       [ 1, -1, -2],
       [ 0, -1,  1]])

In [22]:
(D.T@E)+G

array([[ 3,  0,  2],
       [-3,  5,  6],
       [ 1,  3, -1]])

In [23]:
F@I

array([[0, 3],
       [2, 1]])

In [24]:
I@F@I@I #mozna skrócić z wykorzystaniem F@I

array([[0, 3],
       [2, 1]])

In [25]:
print(np.linalg.det(G)) 
np.linalg.inv(G)

-9.000000000000002


array([[ 0.33333333, -0.33333333,  0.33333333],
       [ 0.11111111,  0.22222222,  0.77777778],
       [ 0.11111111,  0.22222222, -0.22222222]])

In [26]:
print(np.linalg.det(H)) 
np.linalg.inv(H)

1.0


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
print(np.linalg.det(C)) 
np.linalg.inv(C)

-2.2204460492503185e-16


array([[-4.50359963e+15, -4.50359963e+15,  1.66666667e-01,
         4.50359963e+15],
       [ 9.00719925e+15,  9.00719925e+15,  6.66666667e-01,
        -9.00719925e+15],
       [-1.35107989e+16, -1.35107989e+16, -1.50000000e+00,
         1.35107989e+16],
       [-9.00719925e+15, -9.00719925e+15, -1.66666667e+00,
         9.00719925e+15]])

In [28]:
print(np.linalg.det(F)) 
np.linalg.inv(F)

-6.0


array([[-0.16666667,  0.5       ],
       [ 0.33333333,  0.        ]])

In [29]:
w+v

array([[3, 3, 1, 0]])

In [30]:
x@G

array([[ 4,  8, 16]])

In [31]:
G@x #niewłaściwe wymiary macierzy 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [32]:
G@x.T

array([[20],
       [ 8],
       [ 0]])

In [33]:
w@w.T

array([[6]])

In [34]:
w.T@w

array([[1, 2, 1, 0],
       [2, 4, 2, 0],
       [1, 2, 1, 0],
       [0, 0, 0, 0]])

In [35]:
z@z.T

array([[10]])

In [36]:
z.T@z

array([[1, 2, 1, 2],
       [2, 4, 2, 4],
       [1, 2, 1, 2],
       [2, 4, 2, 4]])

In [37]:
I@v.T #niewłaściwe wymiary macierzy i wektora I-2 wiersze,2 kolumny a v 1kolumne,4 wiersze

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [38]:
D@u.T #niewłaściwe wymiary macierzy i wektora

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [39]:
B@C@B.T@G@x.T

array([[264],
       [168],
       [264]])

In [40]:
B@C@z.T

array([[14],
       [10],
       [14]])

In [ ]:
#zadanie 3

In [41]:
np.linalg.det(F)

-6.0

In [42]:
np.linalg.det(G)

-9.000000000000002

In [43]:
np.linalg.det(H)

1.0

In [44]:
np.linalg.det(I)

1.0

In [45]:
np.linalg.inv(F)

array([[-0.16666667,  0.5       ],
       [ 0.33333333,  0.        ]])

In [46]:
np.linalg.inv(G)

array([[ 0.33333333, -0.33333333,  0.33333333],
       [ 0.11111111,  0.22222222,  0.77777778],
       [ 0.11111111,  0.22222222, -0.22222222]])

In [47]:
np.linalg.inv(H)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.linalg.inv(I)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#zadanie 4

In [49]:
np.linalg.eigvals(G)

array([ 1.96973253+0.87212877j,  1.96973253-0.87212877j,
       -1.93946506+0.j        ])

In [50]:
np.linalg.eig(G)

(array([ 1.96973253+0.87212877j,  1.96973253-0.87212877j,
        -1.93946506+0.j        ]),
 array([[-0.72639288+0.j        , -0.72639288-0.j        ,
         -0.48528247+0.j        ],
        [ 0.20593114-0.620725j  ,  0.20593114+0.620725j  ,
         -0.59867515+0.j        ],
        [ 0.00732869-0.21116938j,  0.00732869+0.21116938j,
          0.63725111+0.j        ]]))

In [53]:
np.linalg.eigvalsh(G)

array([-1.46050487,  0.76087672,  2.69962815])

In [51]:
np.linalg.eigvals(I)

array([1., 1.])

In [52]:
np.linalg.eig(I)

(array([1., 1.]),
 array([[1., 0.],
        [0., 1.]]))

In [54]:
np.linalg.eigvalsh(I)

array([1., 1.])

In [55]:
#zadanie5

In [60]:
M=np.array ([[5,8,4,1,2],[9,2,1,7,3]])
M

array([[5, 8, 4, 1, 2],
       [9, 2, 1, 7, 3]])

In [73]:
waga=np.array (((1,1,1,1,1)))
waga

array([1, 1, 1, 1, 1])

In [74]:
sum(waga)

5

In [75]:
M@waga.T/sum(waga) 

array([4. , 4.4])