In [1]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv
from math import sqrt

In [2]:
#Zadanie 1

In [3]:
w=np.array([[1,2,1,0]])
u=np.array([[1,0,-1,1]])
v=np.array([[2,1,0,0]])
A=np.array([[1,0,1,2],[0,1,-2,0]])
B=np.array([[1,2,1,0],[1,0,-1,1],[2,1,0,0]])

In [4]:
A@w.T

array([[2],
       [0]])

In [5]:
A@u.T

array([[2],
       [2]])

In [6]:
A@v.T

array([[2],
       [1]])

In [7]:
A@B.T

array([[2, 2, 2],
       [0, 2, 1]])

In [8]:
#Macierz B 'składa' sie z wektorów w,u,v

In [9]:
#Zadanie 2
#Sprawdź czy wektory są liniowo zależne
G=np.array([[1,-1,1],[1,2,3],[2,-1,2]])
det(G)

-2.0000000000000004

In [10]:
#nie są liniowo zależne

In [11]:
O=np.array([[1,-1,1],[4,4,4],[1,2,1]])
det(O)

0.0

In [12]:
# są liniowo zależne

In [13]:
#Zadanie 3 Policz normy wektorów
v=np.array([[1,-1,1]])
w=np.array([[1,2,3]])
u=np.array([[2,-1,2]])
x=np.array([[1,-1,1]])
y=np.array([[4,4,4]])
z=np.array([[1,2,1]])

In [14]:
sqrt(v@v.T)

1.7320508075688772

In [15]:
sqrt(w@w.T)

3.7416573867739413

In [16]:
sqrt(u@u.T)

3.0

In [21]:
#Zadanie 4 - Dokonaj rzutów wektorów 
print([(x@u.T/u@u.T)*u])

[array([[ 30., -15.,  30.]])]


In [23]:
print([(y@u.T/v@v.T)*v])

[array([[ 36., -36.,  36.]])]


In [27]:
print([(z@u.T/u@u.T)*u])

[array([[12., -6., 12.]])]


In [28]:
print([(z@u.T/u@u.T)*u])

[array([[12., -6., 12.]])]


In [29]:
#Zadanie 5 - Znormalizuj wektory, wykonaj rzutowanie

In [30]:
unorm = u/sqrt(u@u.T)
unorm

array([[ 0.66666667, -0.33333333,  0.66666667]])

In [31]:
vnorm = v/sqrt(v@v.T)
vnorm

array([[ 0.57735027, -0.57735027,  0.57735027]])

In [32]:
wnorm = w/sqrt(w@w.T)
wnorm

array([[0.26726124, 0.53452248, 0.80178373]])

In [33]:
print([(z@unorm.T/unorm@unorm.T)*unorm])

[array([[ 1.33333333, -0.66666667,  1.33333333]])]


In [34]:
print([(x@unorm.T/unorm@unorm.T)*unorm])

[array([[ 3.33333333, -1.66666667,  3.33333333]])]


In [35]:
print([(y@unorm.T/unorm@unorm.T)*unorm])

[array([[ 8., -4.,  8.]])]


In [36]:
print([(x@vnorm.T/vnorm@vnorm.T)*vnorm])

[array([[ 3., -3.,  3.]])]


In [37]:
print([(y@vnorm.T/vnorm@vnorm.T)*vnorm])

[array([[ 4., -4.,  4.]])]


In [38]:
print([(z@vnorm.T/vnorm@vnorm.T)*vnorm])

[array([[ 0., -0.,  0.]])]
